spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/co_film
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/co_film
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: none
#  sql:
#    init:
#      mode:
#      platform: all