spring:
  profiles:
    group:
      local:
        - db
        - nginx
      docker:
        - docker-db
    default: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 5030
