spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/co_film
    username: whiteyesx
    password: whiteyesx
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update