spring:
  profiles:
    active:
      - db
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  address: 192.168.88.22
  port: 8080
