INSERT INTO genre (name)
VALUES ('Western'),
       ('Gangster Movie'),
       ('Detective'),
       ('Drama'),
       ('Historical Film'),
       ('Comedy'),
       ('Melodrama'),
       ('Musical Film'),
       ('Noir'),
       ('Political Film'),
       ('Adventure Movie'),
       ('Fairy'),
       ('Tragedy'),
       ('Tragicomedy');